### ISSUE TITLE
Invalid links to pages

### ISSUE THREAD

**Issue by maxd** [adamcooke/documentation#11]
Hi,

I have installed `documentation` gem to Rails 4.2.0.beta2 project (as described in Installation section of README). But it builds incorrect links to pages (see attachment) i.e. without /docs.

![screen shot 2014-10-17 at 0 37 28](https://cloud.githubusercontent.com/assets/27208/4670231/2780968e-5575-11e4-939a-59f5d276da52.png)

Thanks

**Comment by catphish** [comment]
This is fixed by 01fa4b23ce32011d9670952df1e6e5075222b120
