### ISSUE TITLE
Uninstall Instructions

### ISSUE THREAD

**Issue by itsmrwave** [adamcooke/documentation#14]
Could you include uninstall instructions as well? This modified my DB and a rollback doesn't seem to undo (I'm guessing it's because engines behave as separate apps? ... dunno).

**Comment by adamcooke** [comment]
If you remove the gem, you'll need to add a migration to drop any documentation tables. It's not really designed to be "uninstalled".

**Comment by itsmrwave** [comment]
Aha, makes sense. Seems I got used to `db:rollback` but that will do. :+1:

**Comment by adamcooke** [comment]
`db:rollback` should work as long as the Gem is actually still installed in the application.

**Comment by itsmrwave** [comment]
@adamcooke Yes, it should but the gem didn't copy migrations to my `db/migrations` folder so rollback won't/didn't work. 

Running this ... `bundle exec rake db:migrate documentation:install_guides`  (2nd step in your guides) ... seems to have only applied the migration and modified `db/schema.rb` (I've just tried again).

I thought for engines you need to run something like `$ rake engine_name:install:migrations` to copy these migrations into the application? I think this is how the installation process should be ... (at least the DB part).

Copy 'documentation'  migrations into the application (this step seems to be missing) ...

```
$ bundle exec rake documentation:install:migrations
```

Which will result in something the migration being copied into `db/migrations`

```
Copied migration 20150206175441_create_documentation_pages.documentation.rb from documentation
Copied migration 20150206175442_create_nifty_attachments_table.documentation.rb from documentation
Copied migration 20150206175443_create_documentation_screenshots.documentation.rb from documentation
```

Then apply those migrations using `bundle exec rake db:migrate` etc ... then rollback will work.
