### ISSUE TITLE
Help launching on Amazon EC2 Micro instance (Ubuntu)

### ISSUE THREAD

**Issue by brianjking** [adamcooke/documentation#15]
Hello,

I have a Amazon EC2 Micro Instance using ServerPilot (http://serverpilot.com) and am having trouble getting this loaded.

Can you please help?

Thanks!

**Comment by andretanguy** [comment]
Have you considered using www.viaduct.io rather than Server Pilot? You could get this deployed in about 30 seconds on Viaduct by simply using the Git repository as your code source. Also, ServerPilot looks like it's a shared hosting provider (cPanel etc) which tend to be locked down when it comes to the version of Ruby they run.

**Comment by brianjking** [comment]
@andretanguy & @adamcooke -- I think I just need more verbose instructions to get this up and running. 

Perhaps help on a CentOS server running WHM?

I also setup a viaduct account as per @andretanguy's suggestion -- getting stuck with the gem documentation not being available?

Help! Thanks!

**Comment by andretanguy** [comment]
@brianjking apologies - I forgot Documentation is a gem that you need to include as part of a Rails project. 

I've created a sample Rails app that has the Documentation gem included: https://github.com/andretanguy/documentation-example - you can use that as the source repo for deploying onto Viaduct, however I would recommend you fork my example to your own repo. 

The example will mount the Documentation engine on the root path, so you'll probably want to secure any information you add to it. I've just tested a deploy onto Viaduct using the base settings and all seems to work well. You can see the deployed app at https://doc-example.vdtapp.com/

**Comment by andretanguy** [comment]
@brianjking did you get this running?
