### ISSUE TITLE
rake task exception when running initial import

### ISSUE THREAD

**Issue by andretanguy** [adamcooke/documentation#17]
When trying to run the "documentation:install_guides" rake task on Rails 4.2.1 (using Postgres), I get the error:

rake aborted!
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "authorization"
: SELECT  1 AS one FROM "documentation_pages" WHERE "documentation_pages"."parent_id" = $1 AND "documentation_pages"."parent_id" = $2 AND "documentation_pages"."permalink" = $3 LIMIT 1

**Comment by kaktusyaka** [comment]
Just need to change this file app/models/documenation/page.rb

Need to add this string
has_many :children, ->{ uniq }, :class_name => 'Documentation::Page', :foreign_key => 'parent_id'

and remove this method
def children
      @children ||= begin
        if self.new_record?
          []
        else
          children = self.class.where(:parent_id => self.id)
          children.each { |c| c.parents = [parents, self].flatten }
          children
        end
      end
    end

After that everything will work.

**Comment by adamcooke** [comment]
The purpose of the children method is actually a little more complex than this. We also set the `parents` on each child to avoid needing to load them again and thus speeding up loading of breadcrumbs and other nav items for the children.
